### ISSUE TITLE
Add commands to whitelist other Bots' messages

### ISSUE THREAD

**Issue by djaustin** [Purrito-Bot/purrito#26]
**Is your feature request related to a problem? Please describe.**
Purrito ignores all messages from other bots meaning it cannot act based on outputs from other bots.

**Describe the solution you'd like**
A way to maintain a list of whitelisted bot accounts on each server. Messages sent by bots on this list will be read by Purrito and acted upon if appropriate.

**Describe alternatives you've considered**
None

**Additional context**
From a usability point of view I'd expect people would want to be able to add by the user-facing discord ID e.g. Purrito#7480

We also need to make sure that a separate whitelist is maintained for each server.

Also worth considering if only people with certain roles should be able to run those commands

**Comment by djaustin** [comment]
From a usability point of view I'd expect people would want to be able to add by the user-facing discord ID e.g. Purrito#7480

We also need to make sure that a separate whitelist is maintained for each server.

**Comment by djaustin** [comment]
This needs some thinking about how to approach server-specific data. There's probably a pattern out there we can adopt

**Comment by battmeech** [comment]
With Mongo I think we already have a decent pattern, store the list of bots IDs against a Guild ID and we should be good
